task_name: ''

batch_size: 4
epochs: 100 # fixed
lr: 0.005
weights_init: 'kaiming_uniform' # 'normal' | 'uniform' | 'xavier_normal' | 'xavier_uniform' | 'kaiming_uniform' | 'kaiming_normal'
act_fn: 'leaky' # 'relu' | 'leaky' | 'gelu' | 'silu' | 'tanh'
use_batchnorm: True
use_residuals: True
use_maxpool: False # false
residual_nlayers: 1
b_quantization: 2
reconstruction_loss_weight : 1.0
latent_dim: 16 # fixed
model_type: 'vae' # fixed
add_noise: True # fixed

codebook_loss_weight : 3.2
commitment_loss_weight : 12.37
codebook_size : 70

save_model: False # fixed
eval_images_to_plot: 5 # fixed
base_dir: './experiments' # fixed
num_workers: 2 # fixed
compute_metrics: False # fixed
device: 'cuda'
root_dir: '.' # fixed